import Foundation


let Opportunities: [Opportunity] = [
    Opportunity(lat: 41.844,
                long: -87.71,
                interestTag: .animalWelfare,
                organization: "PAWS Animal Shelter",
                description: "Work at an adoption event and help raise money for our animals",
                date: "August 1, 2026",
                commitment: 3,
                minimumAge: 10,
                logo: "Paws",
                address: "1997 N Clybourn Ave",
                website: "https://www.pawschicago.org/",
                contact: "https://www.pawschicago.org/contact-us"),
    Opportunity(lat: 42.05,
                long: -82.65,
                interestTag: .humanService,
                organization: "Connections for the Homeless",
                description: "Help pack lunches and fundraise for shelters",
                date: "August 4, 2026",
                commitment: 5,
                minimumAge: 12,
                logo: "ConnectionsForHomeless",
                address: "2121 Dewey Avenue",
                website: "https://www.connect2home.org/",
                contact: "https://www.connect2home.org/"),
    Opportunity(lat: 41.89,
                long: -87.62,
                interestTag: .environment,
                organization: "Friends of the Chicago River",
                description: "Join a group clean-up along the River Walk",
                date: "August 6, 2026",
                commitment: 4,
                minimumAge: 13,
                logo: "ChicagoRiver",
                address: "121 W. Wacker Drive",
                website: "https://www.chicagoriver.org/",
                contact: "https://www.chicagoriver.org/contact"),
    Opportunity(lat: 41.87,
                long: -87.68,
                interestTag: .healthcare,
                organization: "Red Cross",
                description: "Support disaster relief, blood drives, and emergency preparedness efforts",
                date: "August 10, 2026",
                commitment: 2,
                minimumAge: 16,
                logo: "RedCross",
                address: "2200 W. Harrison St.",
                website: "https://www.redcross.org/",
                contact: "https://www.redcross.org/contact-us.html?srsltid=AfmBOopOd0weK0OWCZTrU6EBFowAM0nbfwQmLrp6sDlcT1ak_yCVZcJm"),
    Opportunity(lat: 41.94,
                long: -87.69,
                interestTag: .artMusic,
                organization: "Cradles to Crayons",
                description: "Pack clothes and school supplies for the upcoming school year",
                date: "August 15, 2026",
                commitment: 3,
                minimumAge: 12,
                logo: "CradlesToCrayons",
                address: "2500 W. Bradley Place",
                website: "https://www.cradlestocrayons.org/chicago/",
                contact: "https://www.cradlestocrayons.org/chicago/contact-us/"),
    Opportunity(lat: 41.88547,
                long: -87.64425,
                interestTag: .tutoring,
                organization: "Tutoring Chicago",
                description: "Tutor a middle schooler in math, reading, or writing once a week",
                date: "August 15, 2026",
                commitment: 6,
                minimumAge: 15,
                logo: "TutoringChi",
                address: "2145 N. Halsted St.",
                website: "https://www.tutoringchicago.org/",
                contact: "https://www.tutoringchicago.org/contact/"),
    Opportunity(lat: 41.88,
                long: -87.62,
                interestTag: .humanService,
                organization: "The Grace Network",
                description: "Come to our warehouse and pack clothing and hygiene kits for Chicago youth",
                date: "August 18, 2026",
                commitment: 3,
                minimumAge: 10,
                logo: "GraceNetwork",
                address: "200 N. Clark St.",
                website: "https://www.gracenetworkchi.org/",
                contact: "https://www.gracenetworkchi.org/"),
    Opportunity(lat: 41.89740,
                long: -87.62593,
                interestTag: .artMusic,
                organization: "The Clare",
                description: "Play an instrument at our music showcase for our residents",
                date: "August 19, 2026",
                commitment: 1,
                minimumAge: 12,
                logo: "Clare",
                address: "55 E. Pearson St.",
                website: "https://theclare.com/",
                contact: "https://theclare.com/contact/"),
    Opportunity(lat: 41.89192,
                long: -87.63407,
                interestTag: .healthcare,
                organization: "Gilda's Club",
                description: "Work at our front desk and help greet members",
                date: "August 20, 2026",
                commitment: 6,
                minimumAge: 18,
                logo: "GildasClub",
                address: "537 N Wells St",
                website: "https://www.gildasclubchicago.org",
                contact: "https://www.gildasclubchicago.org/ways-to-give/volunteer/"),
    Opportunity(lat: 41.89841,
                long: -87.62476,
                interestTag: .tutoring,
                organization: "Chicago Lights",
                description: "Tutor a middle school student once a week in math",
                date: "Flexible",
                commitment: 1,
                minimumAge: 16,
                logo: "ChiLights",
                address: "126 E Chestnut St.",
                website: "https://chicagolights.org",
                contact: "https://chicagolights.org/tutoring/")
]
