import Foundation


let Opportunities: [Opportunity] = [
    Opportunity(lat: 41.844,
                long: -87.71,
                interestTag: .animalWelfare,
                organization: "PAWS Animal Shelter",
                description: "Rescue, care for, and help find loving homes for homeless animals",
                date: DateComponents(month: 8, day: 1),
                commitment: 3,
                minimumAge: 10,
                logo: "Paws",
                address: "1997 N Clybourn Ave"),
    Opportunity(lat: 42.05,
                long: -82.65,
                interestTag: .humanService,
                organization: "Connections for the Homeless",
                description: "Empower people facing homelessness with food, support, and hope",
                date: DateComponents(month: 8, day: 4),
                commitment: 5,
                minimumAge: 12,
                logo: "ConnectionsForHomeless",
                address: "2121 Dewey Avenue"),
    Opportunity(lat: 41.89,
                long: -87.62,
                interestTag: .humanService,
                organization: "Friends of the Chicago River",
                description: "Help keep the Chicago River clean and healthy for future generations",
                date: DateComponents(month: 8, day: 6),
                commitment: 4,
                minimumAge: 13,
                logo: "ChicagoRiver",
                address: "121 W. Wacker Drive"),
    Opportunity(lat: 41.87,
                long: -87.68,
                interestTag: .humanService,
                organization: "Red Cross",
                description: "Support disaster relief, blood drives, and emergency preparedness efforts",
                date: DateComponents(month: 8, day: 10),
                commitment: 2,
                minimumAge: 16,
                logo: "RedCross",
                address: "2200 W. Harrison St."),
    Opportunity(lat: 41.94,
                long: -87.69,
                interestTag: .artMusic,
                organization: "Cradles to Crayons",
                description: "Provide children with clothing, school supplies, and essentials they need to thrive",
                date: DateComponents(month: 8, day: 16),
                commitment: 3,
                minimumAge: 12,
                logo: "CradlesToCrayons",
                address: "2500 W. Bradley Place"),
    Opportunity(lat: 41.88,
                long: -87.64,
                interestTag: .tutoring,
                organization: "Tutoring Chicago",
                description: "Provide one-on-one tutoring to help students achieve academic success",
                date: DateComponents(month: 8, day: 15),
                commitment: 6,
                minimumAge: 15,
                logo: "TutoringChi",
                address: "2145 N. Halsted St."),
    Opportunity(lat: 41.88,
                long: -87.62,
                interestTag: .humanService,
                organization: "The Grace Network",
                description: "Support local families with food, financial assistance, and essential resources",
                date: DateComponents(month: 8, day: 28),
                commitment: 3,
                minimumAge: 10,
                logo: "GraceNetwork",
                address: "200 N. Clark St."),
    Opportunity(lat: 41.89,
                long: -87.62,
                interestTag: .artMusic,
                organization: "The Clare",
                description: "Brighten seniors' lives through companionship and community engagement",
                date: DateComponents(month: 8, day: 30),
                commitment: 1,
                minimumAge: 12,
                logo: "Clare",
                address: "55 E. Pearson St.")
]
