import Foundation


let Opportunities: [Opportunity] = [
    Opportunity(lat: 41.844,
                long: -87.71,
                interestTag: .animalWelfare,
                organization: "PAWS Animal Shelter",
                description: "Rescue, care for, and help find loving homes for homeless animals",
                date: "August 1, 2026",
                commitment: 3,
                minimumAge: 10,
                logo: "Paws",
                address: "1997 N Clybourn Ave",
                website: "https://www.pawschicago.org/",
                contact: "https://www.pawschicago.org/contact-us"),
    Opportunity(lat: 42.05,
                long: -82.65,
                interestTag: .humanService,
                organization: "Connections for the Homeless",
                description: "Empower people facing homelessness with food, support, and hope",
                date: "August 4, 2026",
                commitment: 5,
                minimumAge: 12,
                logo: "ConnectionsForHomeless",
                address: "2121 Dewey Avenue",
                website: "https://www.connect2home.org/",
                contact: "https://www.connect2home.org/"),
    Opportunity(lat: 41.89,
                long: -87.62,
                interestTag: .environment,
                organization: "Friends of the Chicago River",
                description: "Help keep the Chicago River clean and healthy for future generations",
                date: "August 6, 2026",
                commitment: 4,
                minimumAge: 13,
                logo: "ChicagoRiver",
                address: "121 W. Wacker Drive",
                website: "https://www.chicagoriver.org/",
                contact: "https://www.chicagoriver.org/contact"),
    Opportunity(lat: 41.87,
                long: -87.68,
                interestTag: .healthcare,
                organization: "Red Cross",
                description: "Support disaster relief, blood drives, and emergency preparedness efforts",
                date: "August 10, 2026",
                commitment: 2,
                minimumAge: 16,
                logo: "RedCross",
                address: "2200 W. Harrison St.",
                website: "https://www.redcross.org/",
                contact: "https://www.redcross.org/contact-us.html?srsltid=AfmBOopOd0weK0OWCZTrU6EBFowAM0nbfwQmLrp6sDlcT1ak_yCVZcJm"),
    Opportunity(lat: 41.94,
                long: -87.69,
                interestTag: .artMusic,
                organization: "Cradles to Crayons",
                description: "Provide children with clothing, school supplies, and essentials they need to thrive",
                date: "August 15, 2026",
                commitment: 3,
                minimumAge: 12,
                logo: "CradlesToCrayons",
                address: "2500 W. Bradley Place",
                website: "https://www.cradlestocrayons.org/chicago/",
                contact: "https://www.cradlestocrayons.org/chicago/contact-us/"),
    Opportunity(lat: 41.88,
                long: -87.64,
                interestTag: .tutoring,
                organization: "Tutoring Chicago",
                description: "Provide one-on-one tutoring to help students achieve academic success",
                date: "August 15, 2026",
                commitment: 6,
                minimumAge: 15,
                logo: "TutoringChi",
                address: "2145 N. Halsted St.",
                website: "https://www.tutoringchicago.org/",
                contact: "https://www.tutoringchicago.org/contact/"),
    Opportunity(lat: 41.88,
                long: -87.62,
                interestTag: .humanService,
                organization: "The Grace Network",
                description: "Support local families with food, financial assistance, and essential resources",
                date: "August 18, 2026",
                commitment: 3,
                minimumAge: 10,
                logo: "GraceNetwork",
                address: "200 N. Clark St.",
                website: "https://www.gracenetworkchi.org/",
                contact: "https://www.gracenetworkchi.org/"),
    Opportunity(lat: 41.89,
                long: -87.62,
                interestTag: .artMusic,
                organization: "The Clare",
                description: "Brighten seniors' lives through companionship and community engagement",
                date: "August 20, 2026",
                commitment: 1,
                minimumAge: 12,
                logo: "Clare",
                address: "55 E. Pearson St.",
                website: "https://theclare.com/",
                contact: "https://theclare.com/contact/")
]
